#ifndef __NAMUMARK_H__
#define __NAMUMARK_H__

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
  NODE_NONE = 0x0000,

  /* Block */
  NODE_DOCUMENT,
  NODE_REDIRECT,
  NODE_HEADING,
  NODE_LIST,
  NODE_LIST_ITEM,
  NODE_FOOTNOTE_DEFINITION,
  NODE_BLOCKQUOTE,
  NODE_HORIZONTAL_RULE,
  NODE_TABLE,
  NODE_CATEGORY,

  /* Inline */
  NODE_TEXT,
  NODE_BOLD,
  NODE_ITALIC,
  NODE_UNDERLINE,
  NODE_STRIKETHROUGH,
  NODE_SUPERSCRIPT,
  NODE_SUBSCRIPT,
  NODE_LINK,
  NODE_IMAGE,
  NODE_VIDEO,
  NODE_FOOTNOTE_REFERENCE,
  NODE_MACRO,
  NODE_COMMENT,

  NODE_ADVANCED,
} namumark_node_type;

typedef enum {
  NODE_ADVANCED_NONE = 0x0000,
  NODE_ADVANCED_LITERAL,
  NODE_ADVANCED_SIZING,
  NODE_ADVANCED_COLOR,
  NODE_ADVANCED_FOLDING,
  NODE_ADVANCED_WIKI,
  NODE_ADVANCED_HTML,
} namumark_node_advanced_type;

typedef enum {
  NODE_MACRO_NONE = 0x0000,
  NODE_MACRO_INCLUDE,
  NODE_MACRO_AGE,
  NODE_MACRO_DATE,
  NODE_MACRO_DDAY,
  NODE_MACRO_TOC,
  NODE_MACRO_FOOTNOTE,
  NODE_MACRO_BREAKLINE,
  NODE_MACRO_CLEARFIX,
  NODE_MACRO_PAGECOUNT,
  NODE_MACRO_RUBY,
} namumark_node_macro_type;

#ifdef __cplusplus
}
#endif

#endif
