#ifndef __NAMUMARK_H__
#define __NAMUMARK_H__

#ifdef __cplusplus
extern "C" {
#endif

/**
 * NAMUMARK_NODE_TYPE
 * Definition of namumark syntax types.
 * @see https://namu.wiki/w/나무위키:문법%20도움말
 */
typedef enum {
  NAMUMARK_NODE_NONE = 0x0000,

  /* Block */
  NAMUMARK_NODE_DOCUMENT,
  NAMUMARK_NODE_REDIRECT,
  NAMUMARK_NODE_HEADING,
  NAMUMARK_NODE_LIST,
  NAMUMARK_NODE_LIST_ITEM,
  NAMUMARK_NODE_FOOTNOTE_DEFINITION,
  NAMUMARK_NODE_BLOCKQUOTE,
  NAMUMARK_NODE_HORIZONTAL_RULE,
  NAMUMARK_NODE_TABLE,
  NAMUMARK_NODE_CATEGORY,

  /* Inline */
  NAMUMARK_NODE_TEXT,
  NAMUMARK_NODE_BOLD,
  NAMUMARK_NODE_ITALIC,
  NAMUMARK_NODE_UNDERLINE,
  NAMUMARK_NODE_STRIKETHROUGH,
  NAMUMARK_NODE_SUPERSCRIPT,
  NAMUMARK_NODE_SUBSCRIPT,
  NAMUMARK_NODE_LINK,
  NAMUMARK_NODE_IMAGE,
  NAMUMARK_NODE_VIDEO,
  NAMUMARK_NODE_FOOTNOTE_REFERENCE,
  NAMUMARK_NODE_MACRO,
  NAMUMARK_NODE_COMMENT,

  NAMUMARK_NODE_ADVANCED,
} namumark_node_type;

typedef enum {
  NAMUMARK_NODE_ADVANCED_NONE = 0x0000,
  NAMUMARK_NODE_ADVANCED_LITERAL,
  NAMUMARK_NODE_ADVANCED_SIZING,
  NAMUMARK_NODE_ADVANCED_COLOR,
  NAMUMARK_NODE_ADVANCED_FOLDING,
  NAMUMARK_NODE_ADVANCED_WIKI,
  NAMUMARK_NODE_ADVANCED_HTML,
} namumark_node_advanced_type;

typedef enum {
  NAMUMARK_NODE_MACRO_NONE = 0x0000,
  NAMUMARK_NODE_MACRO_INCLUDE,
  NAMUMARK_NODE_MACRO_AGE,
  NAMUMARK_NODE_MACRO_DATE,
  NAMUMARK_NODE_MACRO_DDAY,
  NAMUMARK_NODE_MACRO_TOC,
  NAMUMARK_NODE_MACRO_FOOTNOTE,
  NAMUMARK_NODE_MACRO_BREAKLINE,
  NAMUMARK_NODE_MACRO_CLEARFIX,
  NAMUMARK_NODE_MACRO_PAGECOUNT,
  NAMUMARK_NODE_MACRO_RUBY,
} namumark_node_macro_type;

typedef enum namumark_node_internal_flags {
  NAMUMARK_NODE_OPEN = (1 << 0),
} namumark_node_internal_flags;

#ifdef __cplusplus
}
#endif

#endif // __NAMUMARK_H__
